import type { Metadata } from "next";
import "./globals.css";
import SessionWrapping from "@/lib/sessionWrapping";

export const metadata: Metadata = {
  title: "VenderApp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapping>
      <html lang="en">
        <body>{children}</body>
      </html>
    </SessionWrapping>
  );
}
